[build]
  [build.server]
    workingDirectory = "server"
    buildCommand = "npm install && npm run build"

  [build.webApp]
    workingDirectory = "webApp"
    buildCommand = "npm install && npm run build"  

[deploy]
  [[services]]
    name = "server"
    startCommand = "npm run dev"  

  [[services]]
    name = "webApp"
    startCommand = "npm run dev" 
