[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "cd webApp && npm install && npm run build", 
  "cd server && npm install"  
]

[start]
cmd = "npm install -g concurrently && concurrently \"cd server && npm run dev\" \"cd webApp && npm run dev\""
