[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.build]
cmds = [
  "cd webApp && npm install && npm run build", 
  "cd server && npm install"  
]

[start]
cmd = "cd server && npm install concurrently && npx concurrently \"npm run dev\" \"cd ../webApp && npm run dev\""
