[phases.setup]
  cmds = [
    "cd server && npm install",
    "cd webApp && npm install"
  ]

[phases.build]
  cmds = [
    "cd webApp && npm run build"
  ]

[phases.start]
  cmds = [
    "cd server && npm start"
  ]
