[providers.node]
version = "18.18.0" # Use the required Node.js version

[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "cd webApp && npm install && npm run build", 
  "cd server && npm install"  
]

[start]
cmd = "cd server && npm install concurrently && npx concurrently \"npm run dev\" \"cd ../webApp && npm run dev\""
