[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "cd webApp && npm install && chmod -R +x node_modules/.bin && npm run build", 
  "cd server && npm install"
]

[start]
cd server && npm install concurrently && npx concurrently "npm run dev" "cd ../webApp && npm run dev"
