[build]
  [build.server]
    workingDirectory = "server"
    buildCommand = "npm install && npm run build"

  [build.webApp]
    workingDirectory = "webApp"
    buildCommand = "npm install && npm run build"

[deploy]
  [[services]]
    name = "server"
    startCommand = "npm run dev"
    envVars = ["PORT=3000", "MONGO_URI"]

  [[services]]
    name = "webApp"
    startCommand = "npm run build && npm run preview"
